version: "3"

services:

  database:
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=hrp
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=0.0.0.0
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
    - MYSQL_DATABASE=hrp
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=user
    - MYSQL_PASSWORD=admin
    - MYSQL_HOST=database
    - MYSQL_PORT=3306
    - MYSQL_ADDRESS=database
    ports:
    - "8081:8081"
    links:
    - "database"
    depends_on:
      - "database"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
